services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: fharina-et-ignis:1.0 
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: fharina_et_ignis
      MYSQL_USER: orellana
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql